#cloud-config
hostname: ubuntu
disable_root: false
timezone: Asia/Tokyo
users:
  - name: admin
    lock_passwd: false
    password: "$6$apprun$kXJj7RduFd0S4eY/TzQ6y4E6L.428gYvtg5Euj1Z9jvU7ikgF5SHQbwKjG0KZFKJK2Ta4MT426.lCEwgqWkML."
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    uid: 1000
write_files:
  - path: /etc/cloudinit/nethygiene-vendor.sh
    permissions: '0755'
    content: |
      #!/usr/bin/bash
      touch /etc/cloudinit/status.excuting
      cp /etc/issue /etc/issue.default
      echo "" >> /etc/issue
      echo "### INITIAL BOOT ###" >> /etc/issue
      echo "Setup in progress, please wait" >> /etc/issue
      echo "" >> /etc/issue
      systemctl restart getty@tty1
      apt update
      apt upgrade -y
      apt install -y arp-scan
      cat /etc/issue.default > /etc/issue
      echo "NetHygiene/ubuntu v0.1.0" >> /etc/issue
      echo "" >> /etc/issue
      echo "#%     ##           *    #      #                  @@                         " >> /etc/issue
      echo "#%%    @#          #@    #      #                                             " >> /etc/issue
      echo "#@%%%  @#  ##%%%% #@@#*  #______#  #*   ## ###%%%% #%  ##%%%%  #v##%%   ##%%%%" >> /etc/issue
      echo "#@  %% @# #%%###%  @@    #======#  %%  ## #@    #% @@ #%%###%  #@   #% #%%###%" >> /etc/issue
      echo "#@   %%%# %@       @%    #      #   %%##  %@   #@@ @@ %@       #@   ## %@     " >> /etc/issue
      echo "##    %%#  %####*  %%##  #      #    %@#   %%@#%@@ %#  %####*  ##   ##  %####*" >> /etc/issue
      echo "                                      ##        ###                           " >> /etc/issue
      echo "                                    *##     *####                             " >> /etc/issue
      echo "" >> /etc/issue
      reboot
  - path: /etc/cron.d/nethygiene
    owner: root:root
    permissions: '0644'
    content: |
      */10 * * * * ubuntu /home/ubuntu/NetHygiene/scan_and_post.sh >> /var/log/scan_and_post.log 2>&1
runcmd:
  - sh /etc/cloudinit/nethygiene-vendor.sh
  - systemctl restart cron
reboot:
  - delay: 10
  - timeout: 600
  - condition: "true"
