#cloud-config
hostname: ubuntu
disable_root: false
timezone: Asia/Tokyo
users:
  - name: admin
    lock_passwd: true
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    uid: 1000
ssh_pwauth: true
ssh-authorized-keys:
  - {{ SSH_PUBLIC_KEY }}
write_files:
  - path: /etc/cloudinit/scan_and_post.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/usr/bin/bash
      cp /etc/issue /etc/issue.default
      echo "" >> /etc/issue
      echo "### INITIAL BOOT ###" >> /etc/issue
      echo "Setup in progress, please wait" >> /etc/issue
      echo "" >> /etc/issue
      systemctl restart getty@tty1
      apt update
      apt upgrade -y
      apt install -y arp-scan sl
      cat /etc/issue.default > /etc/issue
      echo "NetHygiene/ubuntu v0.1.0" >> /etc/issue
      echo "" >> /etc/issue
      echo "       &&&&      &&&&                                                           " >> /etc/issue
      echo "       &&&&&     &&&&            &&                                             " >> /etc/issue
      echo "       &&&&&&    &&&&           &&&                                             " >> /etc/issue
      echo "       &&& &&&   &&&&        &&&&&&&&&&&&                                       " >> /etc/issue
      echo "       &&& &&&&  &&&&  &&&&&&&& &&&                                             " >> /etc/issue
      echo "       &&&  &&&& &&&&&&&&   &&&&&&&                                             " >> /etc/issue
      echo "       &&&   &&&&&&&&&&       &&&&&                                             " >> /etc/issue
      echo "       &&&    &&&&&&&&&&&&&&&&&&&&&  &&&&&                                      " >> /etc/issue
      echo " ;;;;; &&&+;;;;x&&&&&&&          &&& &&&&&                                      " >> /etc/issue
      echo " ;+;+; &&&+;+;++&&&&&&&&&&   &&&  &&&&&&&&                                      " >> /etc/issue
      echo " ;;+;;    +;;+;+       &&&&&&&&    ;;;;;;;     +;;;;++                          " >> /etc/issue
      echo " +;;+;    +;+;;+;;;+   +;;;+       ;+;++;+   ;;+;++;;;;;                        " >> /etc/issue
      echo " ;+;;+;;;;+;;+;+;+;+   ;+;; +;;;;;+;;+;;++  ;+;;    +;+;            +;;;;;;;+   " >> /etc/issue
      echo " ;;+;;+;+;;+;;+++;;;+  ;;++;;+;;++;+;;+;;+  ;;+;;;;;+;;+&&&&&&&&&  ;;++;++;;;;  " >> /etc/issue
      echo " +;;+;    +;+;;+ +;;++;+;+;+;;    ;;+;;+;+  +;;++;+;++;+&&&&&&&&&&++;;;    +;++ " >> /etc/issue
      echo " ;+;;+    +;;+;+  ;+;;;+; ;;+;    +;;+ ;;;++;+;;++;;+;; &&&&  &&&&x;+;+;;;;+;;+ " >> /etc/issue
      echo " ;;+;;    +;+;;+   ;+;+;+ +;;++   ;+;; ;+;;+;;+;;;+;;+; &&&&   &&&$;;+;         " >> /etc/issue
      echo " +;;+;    +;;+;+    ;;+;   +;;;;;+;;+;            +;    &&&&   &&&&+;;+;;+;;++  " >> /etc/issue
      echo " +;;;;    +;;;;+  ;;+;;       +;+;+;;+                  &&&&   &&&& ;;+;;+;;;;  " >> /etc/issue
      echo "               ;;;+;;+     ++    ;;+;;                  &&&&   &&&&             " >> /etc/issue
      echo "                ++++      ;;;;;+;+;;+                                           " >> /etc/issue
      echo "                              ++;                                               " >> /etc/issue
      echo "" >> /etc/issue
  - path: /etc/cron.d/nethygiene
    owner: root:root
    permissions: '0644'
    content: |
      # NetHygiene cron job
      */10 * * * * admin /home/admin/NetHygiene/scan_and_post.sh >> /var/log/scan_and_post.log 2>&1
  - path: /home/admin/NetHygiene/scan_and_post.sh
    owner: admin:admin
    permissions: '0755'
    content: |
      #!/bin/bash

      set -o nounset
      set -o pipefail

      # ---- .env 読み込み ----
      SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
      set -a
      source "${SCRIPT_DIR}/.env"
      set +a

      # ---- ログ設定 ----
      LOG_DIR="${SCRIPT_DIR}/log"
      mkdir -p "$LOG_DIR"
      SUCCESS_LOG="${LOG_DIR}/success.log"
      ERROR_LOG="${LOG_DIR}/error.log"
      TIMESTAMP() { date '+%Y-%m-%d %H:%M:%S%z'; }

      # ---- MACアドレス取得 ----
      mapfile -t MACS < <(arp-scan -q -I "$IFACE" --localnet \
        | grep -oE '([0-9a-f]{2}:){5}[0-9a-f]{2}')

      if [ "${#MACS[@]}" -eq 0 ]; then
        echo "$(TIMESTAMP) No MAC addresses found" | tee -a "$ERROR_LOG" >/dev/null
        exit 1
      fi

      # ---- JSON配列に変換----
      JSON_PAYLOAD=$(printf '"%s",' "${MACS[@]}" | sed 's/,$//')
      JSON_PAYLOAD="[${JSON_PAYLOAD}]"
      # echo "生成されたJSON_PAYLOAD: ${JSON_PAYLOAD}"

      # ---- POST送信 ----
      HTTP_CODE=$(curl -sS -o /dev/null -w '%{http_code}' \
        -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${NET_TOKEN}" \
        -d "$JSON_PAYLOAD" \
        "$NET_HOST")

      # ---- 成功判定 ----
      if [[ "$HTTP_CODE" =~ ^2[0-9]{2}$ ]]; then
        echo "$(TIMESTAMP) Sent MACs (${#MACS[@]} entries) to ${NET_HOST} [HTTP ${HTTP_CODE}]" \
          | tee -a "$SUCCESS_LOG" >/dev/null
        exit 0
      else
        echo "$(TIMESTAMP) Failed to send MACs to ${NET_HOST} [HTTP ${HTTP_CODE}] Payload=${JSON_PAYLOAD}" \
          | tee -a "$ERROR_LOG" >/dev/null
        exit 1
      fi
runcmd:
  - sh /etc/cloudinit/scan_and_post.sh
  - systemctl restart cron
reboot:
  - delay: 10
  - timeout: 600
  - condition: "true"
